name: Go 1.18 compat test

on:
  pull_request:
    branches: ['main']

jobs:
  go118:
    strategy:
      fail-fast: false
      matrix:
        ko-go-version: ['1.17', '1.18']
        user-go-version: ['1.17', '1.18']
    name: Go 1.18 compat (ko=${{ matrix.ko-go-version }} / user=${{ matrix.user-go-version }})
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build ko using ko-go-version
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.ko-go-version }}
        check-latest: true
    - run: go install ./

    # Run ko using user-go-version
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.user-go-version }}
        check-latest: true
    - uses: chainguard-dev/actions/setup-registry@main
    - env:
        KO_DOCKER_REPO: localhost:1338
      run: ko build ./test/
